import logging
import httpx
from fastapi import APIRouter, HTTPException, BackgroundTasks
from app.models.insights import PredictiveInsightsRequest, PredictiveInsightsResponse
from app.services.cache import get_cache, set_cache
from app.config import settings
from app.services.gemini import generate_predictive_insights

logger = logging.getLogger(__name__)
router = APIRouter()

@router.post("/predictive-insights", response_model=PredictiveInsightsResponse)
async def create_predictive_insights(request: PredictiveInsightsRequest, background_tasks: BackgroundTasks):
    """
    On-demand endpoint to generate predictive insights for a specific ward.
    Normally, this is generated by the cron job.
    """
    try:
        # 1. Fetch historical data from Fastify API
        async with httpx.AsyncClient() as client:
            res = await client.get(f"{settings.MAIN_API_URL}/issues/historical/{request.ward}")
            res.raise_for_status()
            data = res.json()
            historical_issues = data.get("data", [])

        if not historical_issues:
            raise HTTPException(status_code=404, detail=f"No historical issues found for ward: {request.ward}")

        # 2. Use Gemini to generate insights
        insights_dict = await generate_predictive_insights(request.ward, historical_issues)
        
        # 3. Cache the result in Redis with a 7-day TTL (604800 seconds)
        cache_key = f"insights:{request.ward}"
        background_tasks.add_task(set_cache, cache_key, insights_dict, 604800)

        return PredictiveInsightsResponse(**insights_dict)

    except Exception as e:
        logger.error(f"Error generating insights for {request.ward}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{ward}", response_model=PredictiveInsightsResponse)
async def get_insights(ward: str):
    """
    Fetches the cached predictive insights for a ward.
    """
    cache_key = f"insights:{ward}"
    cached_data = await get_cache(cache_key)
    
    if cached_data:
        logger.info(f"Cache hit for ward insights: {ward}")
        return PredictiveInsightsResponse(**cached_data)
        
    logger.info(f"Cache miss for ward insights: {ward}")
    raise HTTPException(
        status_code=404, 
        detail=f"Insights not available for {ward}. Please wait for the weekly generation or trigger an on-demand update."
    )
